name = "oeis_a211417_fc"
version = "0.1.0"
defaultTargets = ["OeisA211417FC"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "638da20efd8eeeed2993fc2550fc596dc90c1ce8"

[[lean_lib]]
name = "OeisA211417FC"
